### ISSUE TITLE
Rack issue. Red Dot on "Update Plugins", despite latest version 5.9

### ISSUE THREAD

**Issue by JeffGreenlee42** [modlfo/VultModules#14]
OS:  Windows 10.  
Rack version:  0.5.1

I first reported this to the RACK Issues page but then found that others have reported this issue with other modules. Several were responded to by Andrew Belt that this is a Modules issue, not a Rack issue.  

So I closed the Issue there and am attempting to report it here.   The Red Dot in Rack on the "Update Plugins" button in rack is constantly there.  If I click on the button,  Rack downloads (updates) VULTModules.   

After successful download of VULTmodules Rack shows dialogue, forcing a restart.  
Rack Closes.  
Open Rack again.  Red dot is back.  Click update Modules,  .... Wash and repeat over and over. 
VultModules displays version as "VultMOdules v0.5.9"  That is the latest .. .. (correct?) 

In Rack bugs previously filed, Andrew says this is due to something developers are not updating correctly in the "Slug".   (just search for "Red Dot" to find other bugs. Forgive me.. I am not a developer.. so I am not sure I know what a slug is.") 

Cheers! (love your modules!)

**Comment by modlfo** [comment]
I assume you are on windows since it's the platform that has more problems. Follow these steps and let me know if it worked.
- Go to the Documents folder and then to Rack/plugins
- Delete all the folders and zip files that that have start with the Vult prefix. For example: VultModules, Vult, Vult.zip, VultModules.zip.
- Once the folder is clean open Rack and press the update button to re-download the plugins.
- Go to the Documents/Rack/plugins folder and check that there's one folder called VultModules.
- If there's no folder, check there's a zip file called VultModules.zip. If there's a zip, decompress it.

Now you should have the latest version which is 0.5.10.

**Comment by modlfo** [comment]
@JeffGreenlee42 any success?

**Comment by JeffGreenlee42** [comment]
Hi, I am staying at my families, so don’t have access to my PC at the
moment, but I do have my Mac Mini here I noticed warnings about missing
Vult modules when opening patches (even though the modules are there and
accessible). So I followed your instructions ....removed all Vult module
stuff from plugins folder and clicked the update button. It re-downloaded
(and its v0.5.10) and everything is fine. I’ll try the same when I’m back
on my PC.

Jeff
