### ISSUE TITLE
Windows version Error

### ISSUE THREAD

**Issue by synthi** [modlfo/VultModules#2]
When launching rack.exe with the vultmodules in the plugins directory I have the following error message:
" No se encuentra el punto de entrada del procedimento _ZN4rack11ParamWidget17onMouseDownOpaqueEi en la biblioteca de vinculos dinamicos Rack.exe.

Thats in Spanish, but easy to translate... Cant find the entry point.(....) in the dynamic links Library Rack.exe

Then the VCVRack program loads but the vultmodules are not on the modules list

**Comment by modlfo** [comment]
That happens when the version of the plugins does not match the version of Rack. If you downloaded Rack v0.3.2 you need to use these https://github.com/modlfo/VultModules/releases/download/VCVRack-v0.3.2/VultModules.zip 

If you still have v0.3.1 get these instead https://github.com/modlfo/VultModules/releases/download/VCVRack-v0.3.1/VultModules.zip

Let me know if still doesn't work for you.

**Comment by synthi** [comment]
Was using wrong version, now working fine in 0.3.2 :)

**Comment by modlfo** [comment]
Great!
