### ISSUE TITLE
Rescomb: negative voct (pitch down)

### ISSUE THREAD

**Issue by digitalohm** [modlfo/VultModules#27]
When attempting to tune the voct below midpoint (negative) there is no change in pitch?  Is this user error on my part?

**Comment by patman023** [comment]
It's a comb filter, so you would be getting a narrow-band notch at ~12 (-24?) dB when viewed on a spectrum analyzer or spectrograph.

This is the basis on which a phase-shifter effect is built.

**Comment by digitalohm** [comment]
apologies if I'm not understanding

I made a short video including a vco, rescomb, scope and spectrum analyzer

https://vimeo.com/310176093/fc62757c11

this is the expected behavior (no movement below 12 o clock)?  My previous experience has been with 2hp Comb, Octatrack Comb, and the M4L Comb but only in a tonal sense.  When I see the tune knob I'm thinking this adds a frequency to the original sound?

**Comment by patman023** [comment]
ooh. I see what you mean... paging @modlfo ! Tune has no effect from 7-12 o clock regardless of input or other settings!

and @digitalohm , check out this vid for how this effect specifically works... it doesn't necessarily add to the sound. https://www.youtube.com/watch?v=JgqctTgEj3c

**Comment by modlfo** [comment]
The Tune knob it’s an offset to the pitch input. When there’s no Pitch input, the defaul voltage is 0V. The pitch is given in volts per octave, so when the pitch input is not connected, the Tune knob generates negative voltage (very low pitch). Rescomb has a restriction on the lowest pitch it can “filter” (I don’t remember the exact frequency), but it’s the point where the comb filter does not have any effect on the input audio and it’s starts behaving as a delay. 

This behavior that may seem odd is because, compared to other Comb filters, Rescomb is tuned and uses the V/OCT convention.

The version included in Freak behaves slightly different. The Cutoff knob sets the lowest pitch in the lowest position.

Sorry I cannot give you a more detailed answer because I’m typing in the phone.
