### ISSUE TITLE
[FR] Trummor 2 - V/Oct Tune

### ISSUE THREAD

**Issue by aptrn** [modlfo/VultModules#42]
Hello Leonardo,
I didn't find any other issue about this, if there is one already I'm sorry to bother you.
In most of my drum-equipped patches I'm using your Trummor 2 module as kick drum generator, as it fits nicely in mixes and sounds amazing.
The only thing I'm struggling with is feeding into it a V/Oct signal for Oscillator tuning, as I would do with a modern 808-style bass drum.
Is there a way to make it follow the signal already or could this be implemented in future releases?

Thank you a lot for your work, long time esteemer

**Comment by modlfo** [comment]
You can do it by sending a modulation to the Tune control. To make it more precise, do the following:
- Send your pitch signal to a modulation slot and assign it to the Tune control.
- Put the modulation attenuverter to the maximum.
- Manually enter the Tune value of 0.1 (right click the control).
- This will make Trummor 2 follow 1V/Oct signal with 1V corresponding to C3 (130Hz).

I will try to add in the future a display of the frequency to the Tune control. Apart from that, I won't make further changes to Trummor 2 because changing behaviour would break many patches.

If you use Knock, that one has direct 1V/Oct input signal and it's a more flexible kick that Trummor 2.

**Comment by modlfo** [comment]
<img width="781" alt="Screenshot 2019-10-20 at 09 53 25" src="https://user-images.githubusercontent.com/2001046/67158772-e9f53e00-f344-11e9-9e2d-0aac127ce26b.png">

**Comment by aptrn** [comment]
It was really lazy of me not finding out myself, it was way simper than i thought.
It actually doesn't need any implementation actually, it already does everything I needed as it is now.
Thank you a lot, Leonardo
